version: "3.8"

services:
  node:
    image: node:14
    user: "node"
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    volumes:
      - ./:/home/node/app
    ports:
      - 3001:3001
    command: "npm start"

  mysql:
    image: mysql:8.0
    ports:
      - 33065:3306
    volumes:
      - torn-proxy-mysql-data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: torn-proxy

volumes:
  torn-proxy-mysql-data:
